# Generated by Django 5.1.1 on 2024-09-29 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.courses'),
        ),
    ]
