# Generated by Django 5.1.1 on 2024-09-29 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_events_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='course',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='color',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
