# Generated by Django 5.1.1 on 2024-09-29 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_events_course_events_color_delete_courses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='color',
            new_name='backgroundColor',
        ),
    ]
