# Generated by Django 5.1.1 on 2024-09-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_color_events_backgroundcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='end',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
