# Generated by Django 5.1.1 on 2024-09-29 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_course_notes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='events',
            unique_together=set(),
        ),
    ]
